config/routes.rb
TaskRequestx::Engine.routes.draw do
  resources :requests

  root :to => 'requests#index'
end

app/models/task_requestx/request.rb
module TaskRequestx
  class Request < ActiveRecord::Base
    attr_accessor :task_name, :requested_by_name, :cancelled_noupdate, :completed_noupdate, :expedite_noupdate, :need_delivery_noupdate
    attr_accessible :name, :request_content, :request_date, :requested_by_id, :delivery_instruction, :expected_finish_date, :expedite, 
                    :last_updated_by_id, :need_delivery, :task_id, :what_to_deliver, :cancelled, :completed, :request_status_id, 
                    :task_name, :requested_by_name,
                    :as => :role_new
    attr_accessible :name, :request_content, :request_date, :requested_by_id, :delivery_instruction, :expected_finish_date, :expedite, 
                    :last_updated_by_id, :need_delivery, :task_id, :what_to_deliver, :cancelled, :completed, :request_status_id, 
                    :task_name, :requested_by_name, :cancelled_noupdate, :completed_noupdate, :expedite_noupdate, :need_delivery_noupdate,
                    :as => :role_update                    
    belongs_to :task, :class_name => TaskRequestx.task_class.to_s
    belongs_to :last_updated_by, :class_name => 'Authentify::User'
    belongs_to :requested_by, :class_name => 'Authentify::User'
    belongs_to :request_status, :class_name => 'Commonx::MiscDefinition'

    
    validates_presence_of :request_date, :expected_finish_date
    validates :request_content, :presence => true
    validates :task_id, :request_status_id, :presence => true,
                        :numericality => {:greater_than => 0}
    validates :name, :presence => true,
                     :uniqueness => {:scope => :task_id, :case_sensitive => false, :message => I18n.t('Duplicate Name!')}
  end
end

app/controllers/task_requestx/application_controller.rb
module TaskRequestx
  class ApplicationController < ApplicationController
    include Authentify::SessionsHelper
    include Authentify::AuthentifyUtility
    include Authentify::UsersHelper
    include Authentify::UserPrivilegeHelper
    include Commonx::CommonxHelper
    
    before_filter :require_signin
    before_filter :max_pagination 
    before_filter :check_access_right 
    before_filter :load_session_variable, :only => [:new, :edit]  #for parent_record_id & parent_resource in check_access_right
    after_filter :delete_session_variable, :only => [:create, :update]   #for parent_record_id & parent_resource in check_access_right
    before_filter :view_in_config?
    
    protected
  
    def max_pagination
      @max_pagination = find_config_const('pagination')
    end
    
    def view_in_config?
      @view_in_config = Authentify::AuthentifyUtility.load_view_in_config
    end
  end
end

app/controllers/task_requestx/requests_controller.rb
require_dependency "task_requestx/application_controller"

module TaskRequestx
  class RequestsController < ApplicationController
    before_filter :require_employee
    before_filter :load_parent_record
    
    def index
      @title = t('Task Requests')      
      @requests = params[:task_requestx_requests][:model_ar_r]
      @requests = @requests.where(:task_id => params[:task_id]) if @task
      @requests = @requests.page(params[:page]).per_page(@max_pagination)
      @erb_code = find_config_const('request_index_view', 'task_requestx')
    end
  
    def new
      @title = t('New Task Request')
      @request = TaskRequestx::Request.new
    end
  
    def create
      @request = TaskRequestx::Request.new(params[:request], :as => :role_new)
      @request.last_updated_by_id = session[:user_id]
      @request.requested_by_id = session[:user_id]
      if @request.save
        redirect_to URI.escape(SUBURI + "/authentify/view_handler?index=0&msg=Successfully Saved!")
      else
        flash.now[:error] = t('Data Error. Not Saved!')
        render 'new'
      end
    end
  
    def edit
      @title = t('Edit Task Request')
      @request = TaskRequestx::Request.find_by_id(params[:id])
    end
  
    def update
      @request = TaskRequestx::Request.find_by_id(params[:id])
      @request.last_updated_by_id = session[:user_id]
      if @request.update_attributes(params[:request], :as => :role_update)
        redirect_to URI.escape(SUBURI + "/authentify/view_handler?index=0&msg=Successfully Updated!")
      else
        flash.now[:error] = t('Data Error. Not Updated!')
        render 'edit'
      end
    end
  
    def show
      @title = t('Task Request Info')
      @request = TaskRequestx::Request.find_by_id(params[:id])
      @erb_code = find_config_const('request_show_view', 'task_requestx')
    end
    
    protected
    def load_parent_record
      @task = TaskRequestx.task_class.find_by_id(params[:task_id]) if params[:task_id].present? && params[:task_id].to_i > 0
      @request = TaskRequestx::Request.find_by_id(params[:id]) if params[:id].present?
      @task = TaskRequestx.task_class.find_by_id(TaskRequestx::Request.find_by_id(params[:id]).task_id) if params[:id].present?
      @task = TaskRequestx.task_class.find_by_id(params[:request][:task_id]) if params[:request].present? && params[:request][:task_id].to_i > 0  #for render new if error
    end
  end
end

app/helpers/task_requestx/application_helper.rb
module TaskRequestx
  module ApplicationHelper
  end
end

app/helpers/task_requestx/requests_helper.rb
module TaskRequestx
  module RequestsHelper
  end
end

app/views/task_requestx/requests/_form.html.erb
<% if @view_in_config && @erb_code %>
  <%= render inline: @erb_code %>
<% else %>
<h4><%=@title%></h4>
<%= simple_form_for(@request) do |f| %>    
 
  <%= f.input :task_name, :label => 'Task Name', :readonly => true, :input_html => {:value => eval(TaskRequestx.task_name_in_edit.to_s)}%>
  <%= f.input :name, :label => 'Request Name', :readonly => readonly?(@request, 'name') %>
  <%= f.input :request_date, :label => 'Request Date', :as => :string, :readonly => readonly?(@request, 'request_date') %>
  <%= f.input :requested_by_name, :label => 'Requested By', :readonly => true, :input_html => {:value => @request.requested_by.name} %>
  <%= f.input :request_content, :label => 'Request Content', :input_html => {:rows => 3}, :readonly => readonly?(@request, 'request_content') %>
  <%= f.input :expected_finish_date, :label => 'Finish Date', :as => :string, :readonly => readonly?(@request, 'expected_finish_date') %> 
  <%= f.input :request_status_id, :label => 'Request Status', :collection => Commonx::CommonxHelper.return_misc_definitions('task_status') %> 
  <%= f.input :expedite, :label => 'Expedite', :as => :boolean unless readonly?(@request, 'expedite') %>
  <%= f.input :expedite_noupdate, :label => 'Expedite', :input_html => {:value => (@request.expedite ? t('Yes') : t('No'))} if readonly?(@request, 'expedite') %>
  <%= f.input :need_delivery, :label => 'Need Delivery', :as => :boolean unless readonly?(@request, 'need_delivery') %>
  <%= f.input :need_delivery_noupdate, :label => 'Need Delivery', :input_html => {:value => (@request.need_delivery ? t('Yes') : t('No'))} if readonly?(@request, 'need_delivery') %>
  <div id="task_request_delivery_info">
  <%= f.input :what_to_deliver, :label => 'What to Deliver', :input_html => {:rows => 4}, :readonly => readonly?(@request, 'what_to_deliver') %>
  <%= f.input :delivery_instruction, :label => 'Delivery Instruction', :input_html => {:rows => 4}, :readonly => readonly?(@request, 'delivery_instruction') %>
  </div>
  <%= f.input :cancelled, :label => 'Cancelled', :as => :boolean unless readonly?(@request, 'cancelled') %>
  <%= f.input :cancelled_noupdate, :label => 'Cancelled', :input_html => {:value => (@request.cancelled ? t('Yes') : t('No'))} if readonly?(@request, 'cancelled') %>
  <%= f.input :completed, :label => 'Completed', :as => :boolean unless readonly?(@request, 'completed') %>
  <%= f.input :completed_noupdate, :label => 'Completed', :input_html => {:value => (@request.completed ? t('Yes') : t('No'))} if readonly?(@request, 'completed') %>
  
  <%= link_to t('Back'), SUBURI + "/authentify/view_handler?index=0", :class => BUTTONS_CLS['action'] %>
  <%= f.button :submit, t('Save'), :class => BUTTONS_CLS['action'] %>  
<% end %> 
<% end %>

app/views/task_requestx/requests/_form_list.html.erb
<% if @view_in_config && @erb_code %>
  <%= render inline: ERB.new(@erb_code).result(binding) %>
  
<% else %>
<h4><%=@title %></h4>
<div class="pigination"><%= will_paginate models %></div>
<table class="table table-striped">
  <tr>
    <th>#</th>
    <th><%=t('Task') %></th>
    <th><%=t('Request Name') %></th>
    <th><%=t('Request Date') %></th>
    <th><%=t('Finish Date') %></th>   
    <th><%=t('RequestStatus') %></th>   
    <th><%=t('Completed') %></th>
    <th><%=t('Requested By') %></th>
    <th></th>
    
  </tr>

<% models.each do |r| %>
  <tr>
  	
  	<td><%= link_to r.id.to_s, SUBURI + "/authentify/view_handler?index=1&url=#{request_path(r.id, :task_id => r.task_id)}" %></td>
  	<% if has_action_right?('show', TaskRequestx.task_class.to_s.underscore.pluralize, r.task)%>
  	  <td><%= link_to eval(TaskRequestx.task_name_in_index.to_s), SUBURI + "/authentify/view_handler?index=1&url=#{SUBURI + CGI::escape(eval(TaskRequestx.show_task_path))}" %></td>
  	<% else %>
  	  <td><%= eval(TaskRequestx.task_name_in_index.to_s) %></td>
  	<% end %>
  	<td><%= prt(r, :name) %></td>
  	<td><%= r.request_date.strftime("%Y/%m/%d") %></td>
  	<td><%= r.expected_finish_date.strftime("%Y/%m/%d") %></td>
  	<td><%= prt(r, 'request_status.name') %></td>       
    <td><%= t(prt(r, :completed).to_s) %></td>
    <td><%= prt(r, 'requested_by.name') %></td>  
    <td><%= link_to t('Edit'), SUBURI + "/authentify/view_handler?index=1&url=#{CGI::escape(edit_request_path(r, :parent_record_id => r.task, :parent_resource => TaskRequestx.task_class.to_s.underscore.pluralize))}", :class => BUTTONS_CLS['action']  if has_action_right?('update', params[:controller], r) %> </td>

  </tr>
<% end %>
</table>

<table class="table table-striped">
  <tr>
    <th>
  <%= link_to t('Back'), SUBURI + "/authentify/view_handler?index=0", :class => BUTTONS_CLS['action']  %>
  <%= link_to t('New Task Request'), SUBURI + "/authentify/view_handler?index=1&url=#{CGI::escape(new_request_path(:task_id => @task.id, :parent_record_id => @task.id, :parent_resource => TaskRequestx.task_class.to_s.underscore.pluralize))}", :class => BUTTONS_CLS['action'] if @task && has_action_right?('create', params[:controller], @task) %>
    </th>
  </tr>
</table>

<% end %> 

app/views/task_requestx/requests/_form_new.html.erb
<% if @view_in_config && @erb_code %>
  <%= render inline: @erb_code %>
<% else %>
<h4><%=@title%></h4>
<%= simple_form_for(@request) do |f| %>    
 
  <%= f.input :task_name, :label => 'Task Name', :readonly => true, :input_html => {:value => eval(TaskRequestx.task_name_in_edit.to_s)}%>
  <%= f.input :task_id, :as => :hidden, :input_html => {:value => @task.id }%>
  <%= f.input :name, :label => 'Request Name' %>
  <%= f.input :request_date, :label => 'Request Date', :as => :string %>
  <%= f.input :request_content, :label => 'Request Content', :input_html => {:rows => 3} %>
  <%= f.input :expected_finish_date, :label => 'Finish Date', :as => :string %>  
  <%= f.input :request_status_id, :label => 'Request Status', :collection => Commonx::CommonxHelper.return_misc_definitions('task_status'), :include_blank => true %>
  <%= f.input :expedite, :label => 'Expedite', :as => :boolean  %>
  <%= f.input :need_delivery, :label => 'Need Delivery', :as => :boolean %>
  <div id="task_request_delivery_info">
  <%= f.input :what_to_deliver, :label => 'What to Deliver', :input_html => {:rows => 4} %>  
  <%= f.input :delivery_instruction, :label => 'Delivery Instruction', :input_html => {:rows => 4} %>
  </div>
  
  <%= link_to t('Back'), SUBURI + "/authentify/view_handler?index=0", :class => BUTTONS_CLS['action'] %>
  <%= f.button :submit, t('Save'), :class => BUTTONS_CLS['action'] %>  
<% end %> 
<% end %>

app/views/task_requestx/requests/create.html.erb
<h4>TaskRequests#create</h4>
<p>Find me in app/views/projectx/task_requests/create.html.erb</p>

app/views/task_requestx/requests/edit.html.erb
<div id="main_body">

<%= render 'form' %>
 
</div>

app/views/task_requestx/requests/index.html.erb
<div id="main_body">
	
<%= render partial: 'form_list', locals: {models: @requests} %>

</div>

app/views/task_requestx/requests/new.html.erb
<div id="main_body">
<h4><%#=t(@title)%></h4>

<%= render 'form_new' %>

</div>

app/views/task_requestx/requests/show.html.erb
<% if @view_in_config && @erb_code %>
<%= render inline: ERB.new(@erb_code).result(binding)%>
<% else %>
<div id='main_body'>
<h4><%=@title%> </h4>

<p>
  <b><%=t('Task Name')%>:</b>
  <%= eval(TaskRequestx.task_name_in_edit.to_s) %>
</p>
<p>
  <b><%=t('Request Name')%>:</b>
  <%= @request.name %>
</p> 
<p>
  <b><%=t('Requested By')%>:</b>
  <%= @request.requested_by.name %>
</p> 
<p>
  <b><%=t('Request Status')%>:</b>
  <%= @request.request_status.try(:name) if @request.request_status_id.present? %>
</p> 
<p>
  <b><%=t('Request Date')%>:</b>
  <%= @request.request_date.strftime("%Y/%m/%d") %>
</p> 
<p>
  <b><%=t('Expected Finish Date')%>:</b>
  <%= @request.expected_finish_date.strftime("%Y/%m/%d") %>
</p> 
<p>
  <b><%=t('Expedite')%>:</b>
  <%= @request.expedite ? t('Yes') : t('No') %>
</p> 
<p>
  <b><%=t('Completed')%>:</b>
  <%= @request.completed ? t('Yes') : t('No') %>
</p> 

<p>
  <b><%=t('Cancelled')%>:</b>
  <%= @request.cancelled ? t('Yes') : t('No') %>
</p> 
<p>
  <b><%=t('Last Updated By')%>:</b>
  <%= @request.last_updated_by.name %>
</p>
<p>
  <b>LOG：</b>
  <% Commonx::Log.where('resource_id = ? AND resource_name = ?', @request.id, params[:controller].sub('/', '_')).order("created_at DESC").each do |t| %>
    <li><%= t.created_at.strftime("%Y/%m/%d") %>, &nbsp;<%= t.last_updated_by.name %>, &nbsp; <%= t.log %></li>
  <% end %>
</p>

	<table class="table table-striped">
	  <tr>
	    <th>
	    	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	    	<%= link_to t('Back'), SUBURI + "/authentify/view_handler?index=0", :id => 'close', :class => BUTTONS_CLS['action']%>
	    	<%= link_to t('New Log'), SUBURI + commonx.new_log_path(:resource_id => @request.id, :resource_name => params[:controller], :subaction => 'task_request', :format => :js), :remote => true, 
	                  :id => 'new_log_link', :class => BUTTONS_CLS['action'] if has_action_right?('create_task_request', 'commonx/logs') %>
	    </th>
	  </tr>
	</table>
	
</div>
<% end %>

app/views/task_requestx/requests/update.html.erb
<h4>TaskRequests#update</h4>
<p>Find me in app/views/projectx/task_requests/update.html.erb</p>